# Generated by Django 4.0.6 on 2023-06-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to='images/', width_field='width')),
                ('height', models.PositiveIntegerField(editable=False)),
                ('width', models.PositiveIntegerField(editable=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('visible', models.BooleanField(default=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('local', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=1, max_length=10)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order'],
                'unique_together': {('name', 'slug')},
            },
        ),
    ]
