# Generated by Django 4.0.6 on 2023-06-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='check_btn',
            field=models.CharField(blank=True, default='Check Live', max_length=100, null=True),
        ),
    ]
