# Generated by Django 4.0.6 on 2026-03-26 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        height_field="height", upload_to="images/", width_field="width"
                    ),
                ),
                ("height", models.PositiveIntegerField(editable=False)),
                ("width", models.PositiveIntegerField(editable=False)),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=200)),
                ("visible", models.BooleanField(default=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "check_btn",
                    models.CharField(
                        blank=True, default="Check Live", max_length=100, null=True
                    ),
                ),
                ("local", models.BooleanField(default=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("display_order", models.IntegerField(default=1)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=200, null=True
                    ),
                ),
                ("timeStamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["display_order"],
                "unique_together": {("name", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/images",
                        verbose_name="Project Image",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("timeStamp", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio_app.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Image",
                "verbose_name_plural": "Project Images",
            },
        ),
    ]
